### ISSUE TITLE
OutsideClickHandler renders a div but doesn't support attributes like className

### ISSUE THREAD

**Issue by owlyowl** [airbnb/react-outside-click-handler#35]
Hi team!
Just using this component for the first time and have realised it renders an empty <div> tag wrapping the element detecting click outside for but doesn't support HTML element like attributes like className

I'm happy to fork and PR in if you're happy for me to do so?

**Comment by ljharb** [comment]
This is very intentional - see #33 and https://github.com/airbnb/react-outside-click-handler/issues/13#issuecomment-423205690 and https://github.com/airbnb/react-outside-click-handler/issues/8#issuecomment-408947995 and https://github.com/airbnb/react-outside-click-handler/issues/2#issuecomment-394891534.

**Comment by owlyowl** [comment]
No problem thanks for letting me know
