### ISSUE TITLE
className for the wrapping div

### ISSUE THREAD

**Issue by ryabv** [airbnb/react-outside-click-handler#49]
Could you add a className prop? It will really helpful in some cases

**Comment by ljharb** [comment]
No, this is very intentional - see https://github.com/airbnb/react-outside-click-handler/issues/13#issuecomment-423205690 and https://github.com/airbnb/react-outside-click-handler/issues/8#issuecomment-408947995 and https://github.com/airbnb/react-outside-click-handler/issues/2#issuecomment-394891534.

Duplicate of #35. Duplicate of #33.
