### ISSUE TITLE
No way not to render a div, so please add a classname prop

### ISSUE THREAD

**Issue by stackoverprof** [airbnb/react-outside-click-handler#50]
I need to style it as it is becoming a div parent of some elements

**Comment by ljharb** [comment]
Style its container instead.

This is very intentional - see https://github.com/airbnb/react-outside-click-handler/issues/13#issuecomment-423205690 and https://github.com/airbnb/react-outside-click-handler/issues/8#issuecomment-408947995 and https://github.com/airbnb/react-outside-click-handler/issues/2#issuecomment-394891534.

Duplicate of #49. Duplicate of #35. Duplicate of #33.
